# fly.toml app configuration file for ByAgent.io
# Updated for Singapore region (sin)

app = "byagent-io"
primary_region = "sin"

[build]
  # Оставляем пустым — Fly автоматически соберёт Dockerfile из проекта

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

