# fly.toml app configuration file for Fly.io
# Updated for Node.js (Express/Vite hybrid) app running on port 8080

app = "byagent-io"
primary_region = "fra"

[build]

[http_service]
  # Порт должен совпадать с тем, что указан в Dockerfile (ENV PORT=8080)
  internal_port = 8080
  force_https = true

  # Автоуправление машинами
  auto_stop_machines = "stop"
  auto_start_machines = true

  # Минимум 1 активная машина (чтобы API и бот всегда работали)
  min_machines_running = 1

  # Основной процесс приложения
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
